<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<base href="https://regression-hw1.netlify.app/" target="_blank">

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ben Lawrence">

<title>HW1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="HW1_files/libs/clipboard/clipboard.min.js"></script>
<script src="HW1_files/libs/quarto-html/quarto.js"></script>
<script src="HW1_files/libs/quarto-html/popper.min.js"></script>
<script src="HW1_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="HW1_files/libs/quarto-html/anchor.min.js"></script>
<link href="HW1_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="HW1_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="HW1_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="HW1_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="HW1_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">HW1</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ben Lawrence </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="exercise-0" class="level2">
<h2 class="anchored" data-anchor-id="exercise-0">Exercise 0</h2>
<section id="provide-a-link-to-your-github-page" class="level4">
<h4 class="anchored" data-anchor-id="provide-a-link-to-your-github-page">Provide a link to your github page</h4>
<p>You may access my github repo for this class using this <a href="https://github.com/blawrence5298/Regression2024"><strong>LINK</strong></a></p>
</section>
</section>
<section id="exercise-1" class="level2">
<h2 class="anchored" data-anchor-id="exercise-1">Exercise 1</h2>
<section id="the-following-is-a-regression-summary-from-r-for-a-linear-regression-model-between-an-explanatory-variable-x-and-a-response-variable-y.-the-data-contain-n50-points.-assume-that-all-conditions-for-slr-are-satisfied." class="level4">
<h4 class="anchored" data-anchor-id="the-following-is-a-regression-summary-from-r-for-a-linear-regression-model-between-an-explanatory-variable-x-and-a-response-variable-y.-the-data-contain-n50-points.-assume-that-all-conditions-for-slr-are-satisfied.">The following is a regression summary from R for a linear regression model between an explanatory variable <span class="math inline">\(x\)</span> and a response variable <span class="math inline">\(y\)</span>. The data contain <span class="math inline">\(n=50\)</span> points. Assume that all conditions for SLR are satisfied.</h4>
<p><img src="/HW1_files/figure-html/hw1_rsummary.png" style="width: 80%; height: auto;"></p>
</section>
<section id="part-a" class="level3">
<h3 class="anchored" data-anchor-id="part-a">Part a</h3>
<section id="write-the-equation-for-the-least-squares-regression-line." class="level4">
<h4 class="anchored" data-anchor-id="write-the-equation-for-the-least-squares-regression-line.">Write the equation for the least squares regression line.</h4>
<p>According to the summary provided, <span class="math inline">\(\hat\beta_0 \approx -1.10\)</span> and <span class="math inline">\(\hat\beta_1 \approx 2.26\)</span>. So</p>
<p><span class="math display">\[
\hat y_i=\hat\beta_0+\hat\beta_1x_i=-1.10+2.26x_i
\]</span></p>
</section>
</section>
<section id="part-b" class="level3">
<h3 class="anchored" data-anchor-id="part-b">Part b</h3>
<section id="r-performs-a-t-test-to-test-whether-the-slope-is-significantly-different-than-0.-state-the-null-and-alternative-hypothesis-for-this-test.-based-on-the-p-value-what-is-the-conclusion-of-the-test-i.e.-reject-or-do-not-reject-the-null-hypothesis" class="level4">
<h4 class="anchored" data-anchor-id="r-performs-a-t-test-to-test-whether-the-slope-is-significantly-different-than-0.-state-the-null-and-alternative-hypothesis-for-this-test.-based-on-the-p-value-what-is-the-conclusion-of-the-test-i.e.-reject-or-do-not-reject-the-null-hypothesis">R performs a t-test to test whether the slope is significantly different than 0. State the null and alternative hypothesis for this test. Based on the <span class="math inline">\(p\)</span>-value what is the conclusion of the test? (i.e., reject or do not reject the null hypothesis)</h4>
<p><span class="math inline">\(H_0:\)</span> There is not a significant linear relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>. I.e. <span class="math inline">\(\beta_1=0\)</span>.</p>
<p><span class="math inline">\(H_A\)</span> : There is a significant linear relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>. I.e. <span class="math inline">\(\beta_1 \neq0\)</span>.</p>
<p>Based on the p-value in the summary, we reject the null hypothesis, because there is a near 0 likelihood of obtaining a test statistic as extreme as the missing t-value, which is calculated in part d.</p>
</section>
</section>
<section id="part-c" class="level3">
<h3 class="anchored" data-anchor-id="part-c">Part c</h3>
<section id="calculate-the-missing-p-value-for-the-intercept." class="level4">
<h4 class="anchored" data-anchor-id="calculate-the-missing-p-value-for-the-intercept.">Calculate the missing <span class="math inline">\(p\)</span>-value for the intercept.</h4>
<p>To find the missing p-value we will run a t-test with <span class="math inline">\(H_0: \beta_0=0\)</span> and <span class="math inline">\(H_A : \beta_0 \neq 0\)</span>. We may obtain our t statistic using</p>
<p><span class="math display">\[
T=\frac{\hat\beta_0-0}{se(\hat\beta_0)}
\]</span></p>
<p>Which follows a t-distribution with <span class="math inline">\(n-2\)</span> degrees of freedom. In r we obtain</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>T <span class="ot">=</span> <span class="sc">-</span><span class="fl">1.1016</span><span class="sc">/</span><span class="fl">0.4082</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">pt</span>(T, <span class="at">df=</span><span class="dv">48</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.004790619</code></pre>
</div>
</div>
<p>So <span class="math inline">\(Pr(&gt;|t|)\approx 0.00479\)</span></p>
</section>
</section>
<section id="part-d" class="level3">
<h3 class="anchored" data-anchor-id="part-d">Part d</h3>
<section id="calculate-the-missing-t-statistic-for-the-slope." class="level4">
<h4 class="anchored" data-anchor-id="calculate-the-missing-t-statistic-for-the-slope.">Calculate the missing t-statistic for the slope.</h4>
<p>The missing t-statistic for the slope is given by</p>
<p><span class="math display">\[
T=\frac{\hat\beta_1-0}{se(\hat\beta_1)}
\]</span></p>
<p>We may calculate this in r</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fl">2.2606</span><span class="sc">/</span><span class="fl">0.0981</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 23.04383</code></pre>
</div>
</div>
<p>So <span class="math inline">\(T\approx23.0\)</span>.</p>
</section>
</section>
<section id="part-e" class="level3">
<h3 class="anchored" data-anchor-id="part-e">Part e</h3>
<section id="calculate-a-95-confidence-interval-for-the-slope-of-the-regression-line.-does-this-interval-agree-with-the-results-of-the-hypothesis-test" class="level4">
<h4 class="anchored" data-anchor-id="calculate-a-95-confidence-interval-for-the-slope-of-the-regression-line.-does-this-interval-agree-with-the-results-of-the-hypothesis-test">Calculate a 95% confidence interval for the slope of the regression line. Does this interval agree with the results of the hypothesis test?</h4>
<p>The confidence interval for the slope of the regression line may be calculated using</p>
<p><span class="math display">\[
\hat\beta_1 \pm t(1-\frac{0.95}{2},n-2)se(\hat\beta_1)
\]</span> In r we obtain</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>lower_limit <span class="ot">=</span> <span class="fl">2.2606</span> <span class="sc">-</span> <span class="fu">qt</span>(<span class="fl">0.975</span>,<span class="dv">48</span>)<span class="sc">*</span><span class="fl">0.0981</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>upper_limit <span class="ot">=</span> <span class="fl">2.2606</span> <span class="sc">+</span> <span class="fu">qt</span>(<span class="fl">0.975</span>,<span class="dv">48</span>)<span class="sc">*</span><span class="fl">0.0981</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(lower_limit,upper_limit,<span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>2.063357 2.457843 </code></pre>
</div>
</div>
<p>So our confidence interval is approximately <span class="math inline">\((2.06,2.46)\)</span>. This agrees with the results of our hypothesis test. We are 95% confident that <span class="math inline">\(\beta_1\)</span> (the population slope) will fall in the interval. Since the interval does not include 0, this supports the alternative hypothesis that <span class="math inline">\(\beta_1 \neq 0\)</span>.</p>
</section>
</section>
</section>
<section id="exercise-2" class="level2">
<h2 class="anchored" data-anchor-id="exercise-2">Exercise 2</h2>
<section id="consider-the-linear-regression-model-through-the-origin-given-by-y_ibeta-x_ie_i-for-i1cdotsn.-assume-e_isim-n0sigma2-that-is-the-errors-are-independent-and-normally-distributed-with-constant-variance." class="level4">
<h4 class="anchored" data-anchor-id="consider-the-linear-regression-model-through-the-origin-given-by-y_ibeta-x_ie_i-for-i1cdotsn.-assume-e_isim-n0sigma2-that-is-the-errors-are-independent-and-normally-distributed-with-constant-variance.">Consider the linear regression model through the origin given by <span class="math inline">\(Y_i=\beta x_i+e_i\)</span> for <span class="math inline">\(i=1,\cdots,n\)</span>. Assume <span class="math inline">\(e_i\sim N(0,\sigma^2)\)</span>, that is, the errors are independent and normally distributed with constant variance.</h4>
</section>
<section id="part-a-1" class="level3">
<h3 class="anchored" data-anchor-id="part-a-1">Part a</h3>
<section id="show-that-the-least-squares-regression-estimate-of-the-slope-is-given-by" class="level4">
<h4 class="anchored" data-anchor-id="show-that-the-least-squares-regression-estimate-of-the-slope-is-given-by">Show that the least squares regression estimate of the slope is given by</h4>
<p><span class="math display">\[
\hat\beta=\frac{\sum_{i=1}^nx_iy_i}{\sum_{i=1}^nx_i^2}
\]</span></p>
<p>Note that <span class="math inline">\(R(\hat\beta)=\sum_{i=1}^n(y_i-\hat\beta x_i)^2\)</span>.</p>
<p>To minimize <span class="math inline">\(R(\hat\beta)\)</span> we take its derivative and will calculate the critical value(s) by setting the derivative equal to zero.</p>
<p><span class="math display">\[
\begin{align*}
\frac{dR}{d\hat\beta}=-2\sum_{i=1}^nx_i(y_i-\hat\beta x_i)\\
-2\sum_{i=1}^nx_i(y_i-\hat\beta x_i)=0\\
\implies \sum_{i=1}^nx_i(y_i-\hat\beta x_i)=0\\
\implies \sum_{i=1}^n(x_iy_i-\hat\beta x_i^2)=0\\
\implies \sum_{i=1}^nx_iy_i-\sum_{i=1}^n\hat\beta x_i^2=0\\
\implies \hat\beta\sum_{i=1}^n x_i^2=\sum_{i=1}^nx_iy_i\\
\implies\hat\beta=\frac{\sum_{i=1}^nx_iy_i}{\sum_{i=1}^nx_i^2} \checkmark
\end{align*}
\]</span></p>
</section>
</section>
<section id="part-b-1" class="level3">
<h3 class="anchored" data-anchor-id="part-b-1">Part b</h3>
<section id="show-that-ehatbetabeta." class="level4">
<h4 class="anchored" data-anchor-id="show-that-ehatbetabeta.">Show that <span class="math inline">\(E(\hat\beta)=\beta\)</span>.</h4>
<p>First note that if <span class="math inline">\(\hat\beta_0=0\)</span>, then the observed values are given by <span class="math inline">\(y_i=\beta x_i+e_i\)</span></p>
<p>As we demonstrated in part a, <span class="math inline">\(\hat\beta=\frac{\sum_{i=1}^n x_iy_i}{\sum_{i=1}^n x_i^2}\)</span></p>
<p>Substituting for <span class="math inline">\(y_i\)</span> we obtain</p>
<p><span class="math display">\[\hat\beta=\frac{\sum x_i(\beta x_i+e_i)}{\sum x_i^2}=\frac{\sum \beta x_i^2+e_ix_i}{\sum x_i^2}=\beta\frac{\sum x_i^2}{\sum x_i^2}+\frac{\sum e_ix_i}{\sum x_i^2}=\beta +\frac{\sum e_ix_i}{\sum x_i^2}\]</span></p>
<p>Thus the expected value of <span class="math inline">\(\hat\beta\)</span> is given by</p>
<p><span class="math display">\[
E(\hat\beta)=E(\beta) +E(\frac{\sum e_ix_i}{\sum x_i^2})
\]</span></p>
<p>Note that <span class="math inline">\(\beta\)</span> and <span class="math inline">\(x_i\)</span> are not random variables, and we assume that the <span class="math inline">\(e_i\)</span>s are normally distributed with mean zero. Thus we may apply the expectations in the following manner</p>
<p><span class="math display">\[
E(\hat\beta)=\beta+\frac{\sum E(e_i x_i)}{\sum x_i^2}=\beta+\frac{\sum x_iE(e_i)}{\sum x_i^2}=\beta+\frac{0}{\sum x_i^2 }\\
\space\\
=\beta \checkmark
\]</span></p>
</section>
</section>
<section id="part-c-1" class="level3">
<h3 class="anchored" data-anchor-id="part-c-1">Part c</h3>
<section id="show-that-varhatbetafracsigma2sum_i1nx_i2." class="level4">
<h4 class="anchored" data-anchor-id="show-that-varhatbetafracsigma2sum_i1nx_i2.">Show that <span class="math inline">\(Var(\hat\beta)=\frac{\sigma^2}{\sum_{i=1}^nx_i^2}\)</span>.</h4>
<p>We may follow a similar approach when taking the variance of <span class="math inline">\(\hat\beta\)</span> .</p>
<p><span class="math display">\[
Var(\hat\beta) = Var(\beta+\frac{\sum e_i x_i}{\sum x_i^2})=Var(\beta) + Var( \frac{\sum e_ix_i}{\sum x_i^2})
\]</span></p>
<p>Since <span class="math inline">\(\beta\)</span> is not a random variable, we take its variance to be zero</p>
<p><span class="math display">\[
Var(\hat\beta) = 0+Var(\frac{\sum e_i x_i}{\sum x_i^2})=\frac{Var(\sum e_ix_i)}{\sum x_i^2\sum x_i^2}=\frac{\sum x_i^2Var(e_i)}{\sum x_i^2\sum x_i^2}=\frac{Var(e_i)}{\sum x_i^2}
\]</span></p>
<p>And from our assumptions we also know that <span class="math inline">\(Var(e_i) = \sigma^2\)</span> , thus</p>
<p><span class="math display">\[
Var(\hat\beta) = \frac{\sigma^2}{\sum_{i=1}^n x_i^2} \checkmark
\]</span></p>
</section>
</section>
</section>
<section id="exercise-3" class="level2">
<h2 class="anchored" data-anchor-id="exercise-3">Exercise 3</h2>
<section id="the-website-www.playbill.com-provides-weekly-reports-on-the-box-office-ticket-sales-for-plays-on-broadway-in-new-york.-we-shall-consider-the-data-for-the-week-october-11-17-2004-referred-to-below-as-current-week.-the-data-are-in-the-form-of-the-gross-box-office-results-for-the-current-week-and-the-gross-box-office-results-for-the-previous-week-i.e.-october-3-10-2004.-the-data-are-available-on-the-book-website-httpgattonweb.uky.edusheatherbook-in-the-file-playbill.csv" class="level4">
<h4 class="anchored" data-anchor-id="the-website-www.playbill.com-provides-weekly-reports-on-the-box-office-ticket-sales-for-plays-on-broadway-in-new-york.-we-shall-consider-the-data-for-the-week-october-11-17-2004-referred-to-below-as-current-week.-the-data-are-in-the-form-of-the-gross-box-office-results-for-the-current-week-and-the-gross-box-office-results-for-the-previous-week-i.e.-october-3-10-2004.-the-data-are-available-on-the-book-website-httpgattonweb.uky.edusheatherbook-in-the-file-playbill.csv">The website <a href="https://www.playbill.com/">www.playbill.com</a> provides weekly reports on the box office ticket sales for plays on Broadway in New York. We shall consider the data for the week October 11-17, 2004 (referred to below as current week). The data are in the form of the gross box office results for the current week and the gross box office results for the previous week (i.e., October 3-10, 2004). The data are available on the book website <a href="http://gattonweb.uky.edu/sheather/book/" class="uri">http://gattonweb.uky.edu/sheather/book/</a> in the file playbill.csv</h4>
</section>
<section id="fit-the-following-model-to-the-data-ysim-beta_0beta_1xe-where-y-is-the-gross-box-office-results-for-the-current-week-in-dollars-and-x-is-the-gross-box-office-result-for-the-previous-week-in-dollars.-complete-the-following-tasks" class="level4">
<h4 class="anchored" data-anchor-id="fit-the-following-model-to-the-data-ysim-beta_0beta_1xe-where-y-is-the-gross-box-office-results-for-the-current-week-in-dollars-and-x-is-the-gross-box-office-result-for-the-previous-week-in-dollars.-complete-the-following-tasks">Fit the following model to the data: <span class="math inline">\(Y\sim \beta_0+\beta_1x+e\)</span>, where <span class="math inline">\(Y\)</span> is the gross box office results for the current week (in dollars) and <span class="math inline">\(x\)</span> is the gross box office result for the previous week (in dollars). Complete the following tasks:</h4>
</section>
<section id="part-a-2" class="level3">
<h3 class="anchored" data-anchor-id="part-a-2">Part a</h3>
<section id="use-read.csv-to-load-the-playbill.csv-data-file-into-r.-make-a-scatter-plot-of-the-response-versus-the-explanatory-variable-and-superimpose-the-least-squares-regression-line." class="level4">
<h4 class="anchored" data-anchor-id="use-read.csv-to-load-the-playbill.csv-data-file-into-r.-make-a-scatter-plot-of-the-response-versus-the-explanatory-variable-and-superimpose-the-least-squares-regression-line.">Use <strong>read.csv()</strong> to load the playbill.csv data file into R. Make a scatter plot of the response versus the explanatory variable, and superimpose the least squares regression line.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">#reading the csv</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">"playbill.csv"</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Making a scatter plot of the Sales from the Current Week vs. the Sales from Last Week</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(data<span class="sc">$</span>LastWeek, data<span class="sc">$</span>CurrentWeek, <span class="at">main=</span><span class="st">"Current Sales vs Previous"</span>, <span class="at">xlab=</span><span class="st">"Last Week"</span>, <span class="at">ylab=</span><span class="st">"Current Week"</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Adding a Least Squares Regression Line</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>model <span class="ot">=</span> <span class="fu">lm</span>(CurrentWeek <span class="sc">~</span> LastWeek,<span class="at">data=</span>data)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(model, <span class="at">col=</span><span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="HW1_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="part-b-2" class="level3">
<h3 class="anchored" data-anchor-id="part-b-2">Part b</h3>
<section id="calculate-a-95-confidence-interval-for-the-intercept-and-slope-of-the-regression-model-beta_0-and-beta_1.-is-1-a-plausible-value-for-beta_1" class="level4">
<h4 class="anchored" data-anchor-id="calculate-a-95-confidence-interval-for-the-intercept-and-slope-of-the-regression-model-beta_0-and-beta_1.-is-1-a-plausible-value-for-beta_1">Calculate a 95% confidence interval for the intercept and slope of the regression model, <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>. Is <span class="math inline">\(1\)</span> a plausible value for <span class="math inline">\(\beta_1\)</span>?</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Summary of the Least Squares Model</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = CurrentWeek ~ LastWeek, data = data)

Residuals:
   Min     1Q Median     3Q    Max 
-36926  -7525  -2581   7782  35443 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 6.805e+03  9.929e+03   0.685    0.503    
LastWeek    9.821e-01  1.443e-02  68.071   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 18010 on 16 degrees of freedom
Multiple R-squared:  0.9966,    Adjusted R-squared:  0.9963 
F-statistic:  4634 on 1 and 16 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>From the summary we construct the confidence interval for the intercept with</p>
<p><span class="math display">\[
\hat{\beta_0}\pm t(\frac{0.05}{2},n-2)se(\hat{\beta_0}) = 6805\pm t(0.025,16)(9929)
\]</span></p>
<p>Using r, we obtain the interval.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>lower_limit <span class="ot">=</span> <span class="dv">6805</span> <span class="sc">-</span> <span class="fu">qt</span>(<span class="fl">0.975</span>,<span class="dv">16</span>)<span class="sc">*</span>(<span class="dv">9929</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>upper_limit <span class="ot">=</span> <span class="dv">6805</span> <span class="sc">+</span> <span class="fu">qt</span>(<span class="fl">0.975</span>,<span class="dv">16</span>)<span class="sc">*</span>(<span class="dv">9929</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Lower limit:"</span>, lower_limit, <span class="st">"</span><span class="sc">\n</span><span class="st">Upper limit:"</span>, upper_limit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Lower limit: -14243.54 
Upper limit: 27853.54</code></pre>
</div>
</div>
<p>A similar method may be used to obtain a confidence interval for the slope. For the sake of efficiency, the confint( ) function will be used to confirm the above result and obtain the slope’s interval.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(model,<span class="at">level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    2.5 %       97.5 %
(Intercept) -1.424433e+04 27854.099443
LastWeek     9.514971e-01     1.012666</code></pre>
</div>
</div>
<p>1 is a Plausible value for <span class="math inline">\(\beta_1\)</span> because it lies within the confidence interval.</p>
</section>
</section>
<section id="part-c-2" class="level3">
<h3 class="anchored" data-anchor-id="part-c-2">Part c</h3>
<section id="use-the-fitted-regression-model-to-estimate-the-gross-box-office-results-for-the-current-week-in-dollars-for-a-production-with-400000-in-gross-box-office-the-previous-week.-find-a-95-prediction-interval-for-the-gross-box-office-results-for-the-current-week-in-dollars-for-a-production-with-400000-in-gross-box-office-the-previous-week.-is-450000-a-feasible-value-for-the-gross-box-office-results-in-the-current-week-for-a-production-with-400000-in-gross-box-office-the-previous-week" class="level4">
<h4 class="anchored" data-anchor-id="use-the-fitted-regression-model-to-estimate-the-gross-box-office-results-for-the-current-week-in-dollars-for-a-production-with-400000-in-gross-box-office-the-previous-week.-find-a-95-prediction-interval-for-the-gross-box-office-results-for-the-current-week-in-dollars-for-a-production-with-400000-in-gross-box-office-the-previous-week.-is-450000-a-feasible-value-for-the-gross-box-office-results-in-the-current-week-for-a-production-with-400000-in-gross-box-office-the-previous-week">Use the fitted regression model to estimate the gross box office results for the current week (in dollars) for a production with $400,000 in gross box office the previous week. Find a 95% prediction interval for the gross box office results for the current week (in dollars) for a production with $400,000 in gross box office the previous week. Is $450,000 a feasible value for the gross box office results in the current week, for a production with $400,000 in gross box office the previous week?</h4>
<p>We proceed by calculating the key values needed for the prediction interval</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co">#mean of the previous week sales</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>x_bar <span class="ot">=</span> <span class="fu">mean</span>(data<span class="sc">$</span>LastWeek)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>x_bar</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 622186.6</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co">#sum of squares of the previous</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>SXX <span class="ot">=</span> <span class="fu">sum</span>((data<span class="sc">$</span>LastWeek <span class="sc">-</span> x_bar)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>SXX</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.557916e+12</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co">#variance of the residuals</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>S <span class="ot">=</span> <span class="fu">summary</span>(model)<span class="sc">$</span>sigma</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>S</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 18007.56</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co">#estimate of current week sales</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>y_hat <span class="ot">=</span> <span class="fu">predict</span>(model, <span class="fu">data.frame</span>(<span class="at">LastWeek=</span><span class="dv">400000</span>))</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(y_hat, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>399637.5 </code></pre>
</div>
</div>
<p>The prediction interval is given by</p>
<p><span class="math display">\[
\hat{y}^*\pm t(\alpha/2,n-2)S\sqrt{(1+\frac{1}{n}+\frac{(x^*-\bar{x})^2}{SXX})}
\]</span></p>
<p>which we may calculate using r</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculate the interval direcly</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>lower_bound <span class="ot">=</span> y_hat <span class="sc">-</span> <span class="fu">qt</span>(<span class="fl">0.975</span>,<span class="dv">16</span>)<span class="sc">*</span>S<span class="sc">*</span><span class="fu">sqrt</span>((<span class="dv">1</span><span class="sc">+</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">18</span>)<span class="sc">+</span>((<span class="dv">400000</span> <span class="sc">-</span> x_bar)<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span>(SXX)))</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>upper_bound <span class="ot">=</span> y_hat <span class="sc">+</span> <span class="fu">qt</span>(<span class="fl">0.975</span>,<span class="dv">16</span>)<span class="sc">*</span>S<span class="sc">*</span><span class="fu">sqrt</span>((<span class="dv">1</span><span class="sc">+</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">18</span>)<span class="sc">+</span>((<span class="dv">400000</span> <span class="sc">-</span> x_bar)<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span>(SXX)))</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Lower bound:"</span>, lower_bound, <span class="st">"</span><span class="sc">\n</span><span class="st">Upper bound:"</span>, upper_bound, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Lower bound: 359832.8 
Upper bound: 439442.2 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Confirm calculation using the predict function</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(model, <span class="fu">data.frame</span>(<span class="at">LastWeek =</span> <span class="dv">400000</span>), <span class="at">interval =</span> <span class="st">"prediction"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 399637.5 359832.8 439442.2</code></pre>
</div>
</div>
<p>We can see that $450,000 is outside the upper bound of this interval, which indicates it is likely not a feasible value for a production with $400,000 in sales in the previous week.</p>
</section>
</section>
<section id="part-d-1" class="level3">
<h3 class="anchored" data-anchor-id="part-d-1">Part d</h3>
<section id="some-promoters-of-broadway-use-the-prediction-rule-that-next-weeks-gross-box-office-results-will-be-equal-to-this-weeks-gross-box-office-results.-comment-on-the-appropriateness-of-this-rule." class="level4">
<h4 class="anchored" data-anchor-id="some-promoters-of-broadway-use-the-prediction-rule-that-next-weeks-gross-box-office-results-will-be-equal-to-this-weeks-gross-box-office-results.-comment-on-the-appropriateness-of-this-rule.">Some promoters of Broadway use the prediction rule that next week’s gross box office results will be equal to this week’s gross box office results. Comment on the appropriateness of this rule.</h4>
<p>We may investigate this rule by finding a prediction interval for every predictor value in our sample.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Create a new data frame with the values of LastWeek</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>new_data <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">LastWeek =</span> data<span class="sc">$</span>LastWeek)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(new_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  LastWeek
1   695437
2   498969
3   598576
4   528994
5   562964
6   282778</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Use the predict function to find a prediction interval for each value</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>intervals <span class="ot">=</span> <span class="fu">predict</span>(model, new_data, <span class="at">interval=</span><span class="st">"prediction"</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="co">#We check to see if the each value in new_data lies within it's interval</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>within_interval <span class="ot">=</span> new_data<span class="sc">$</span>LastWeek <span class="sc">&gt;=</span> intervals[, <span class="st">"lwr"</span>] <span class="sc">&amp;</span> new_data<span class="sc">$</span>LastWeek <span class="sc">&lt;=</span> intervals[, <span class="st">"upr"</span>]</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a new data frame to display results</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>results <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">LastWeek =</span> new_data<span class="sc">$</span>LastWeek, <span class="at">LowerBound =</span> intervals[, <span class="st">"lwr"</span>], <span class="at">UpperBound =</span> intervals[, <span class="st">"upr"</span>], <span class="at">WithinInterval =</span> within_interval)</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  LastWeek LowerBound UpperBound WithinInterval
1   695437   650496.4   729065.0           TRUE
2   498969   457432.1   536234.1           TRUE
3   598576   555428.3   633882.3           TRUE
4   528994   486996.3   565643.9           TRUE
5   562964   520419.2   598943.6           TRUE
6   282778   243945.1   325086.8           TRUE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Count the number of FALSE in the WithinInterval column</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>false_count <span class="ot">=</span> <span class="fu">sum</span>(<span class="sc">!</span>results<span class="sc">$</span>WithinInterval)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the count</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Number of times WithinInterval is FALSE:"</span>, false_count, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Number of times WithinInterval is FALSE: 0 </code></pre>
</div>
</div>
<p>We can see here that each value in our sample for LastWeek lies within its prediction interval. Meaning that it is plausible that next week’s gross results could be equal to the previous week’s. However the intervals are somewhat large with respect to sales numbers. It is also plausible that a production which made $695,437 in the previous week could make anywhere from $650,496 to $729,065 in the next week. This is a difference of tens of thousands of dollars and is likely relevant for Broadway promoters. So while the rule is a useful starting point, the variation makes it impractical to rely upon.</p>
</section>
</section>
</section>
<section id="exercise-4" class="level2">
<h2 class="anchored" data-anchor-id="exercise-4">Exercise 4</h2>
<section id="for-this-question-use-the-oldfaith-data-set-from-the-alr4-package.-the-oldfaith-data-set-gives-information-about-eruptions-of-the-old-faithful-geyser-during-october-1980.-variables-are-duration-in-seconds-of-the-current-eruption-and-the-interval-the-time-in-minutes-to-the-next-eruption.-the-data-were-collected-by-volunteers-and-were-provided-by-the-late-roderick-hutchinson.-apart-from-missing-data-for-the-period-from-midnight-to-6-a.m.-this-is-a-complete-record-of-eruptions-for-that-month." class="level4">
<h4 class="anchored" data-anchor-id="for-this-question-use-the-oldfaith-data-set-from-the-alr4-package.-the-oldfaith-data-set-gives-information-about-eruptions-of-the-old-faithful-geyser-during-october-1980.-variables-are-duration-in-seconds-of-the-current-eruption-and-the-interval-the-time-in-minutes-to-the-next-eruption.-the-data-were-collected-by-volunteers-and-were-provided-by-the-late-roderick-hutchinson.-apart-from-missing-data-for-the-period-from-midnight-to-6-a.m.-this-is-a-complete-record-of-eruptions-for-that-month.">For this question use the oldfaith data set from the alr4 package. The oldfaith data set gives information about eruptions of the Old Faithful Geyser during October 1980. Variables are Duration in seconds of the current eruption, and the Interval, the time in minutes to the next eruption. The data were collected by volunteers and were provided by the late Roderick Hutchinson. Apart from missing data for the period from midnight to 6 a.m., this is a complete record of eruptions for that month.</h4>
</section>
<section id="part-a-3" class="level3">
<h3 class="anchored" data-anchor-id="part-a-3">Part a</h3>
<section id="use-the-lm-function-to-perform-a-simple-linear-regression-with-interval-as-the-response-and-duration-as-the-predictor.-use-the-summary-function-to-print-the-results." class="level4">
<h4 class="anchored" data-anchor-id="use-the-lm-function-to-perform-a-simple-linear-regression-with-interval-as-the-response-and-duration-as-the-predictor.-use-the-summary-function-to-print-the-results.">Use the lm() function to perform a simple linear regression with Interval as the response and Duration as the predictor. Use the summary() function to print the results.</h4>
<p>Here we read in the OldFaith dataset, create our linear model, and obtain a summary</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">#reading the csv</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">"OldFaith.csv"</span>)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="co"># linear regression model</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>model <span class="ot">=</span> <span class="fu">lm</span>(Interval <span class="sc">~</span> Duration,<span class="at">data=</span>data)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a><span class="co">#regression summary</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Interval ~ Duration, data = data)

Residuals:
     Min       1Q   Median       3Q      Max 
-12.3337  -4.5250   0.0612   3.7683  16.9722 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 33.987808   1.181217   28.77   &lt;2e-16 ***
Duration     0.176863   0.005352   33.05   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.004 on 268 degrees of freedom
Multiple R-squared:  0.8029,    Adjusted R-squared:  0.8022 
F-statistic:  1092 on 1 and 268 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
</section>
<section id="part-b-3" class="level3">
<h3 class="anchored" data-anchor-id="part-b-3">Part b</h3>
<section id="make-a-scatter-plot-of-interval-vs.-duration.-superimpose-the-least-squares-regression-line-on-the-scatter-plot." class="level4">
<h4 class="anchored" data-anchor-id="make-a-scatter-plot-of-interval-vs.-duration.-superimpose-the-least-squares-regression-line-on-the-scatter-plot.">Make a scatter plot of Interval vs.&nbsp;Duration. Superimpose the least squares regression line on the scatter plot.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co">#scatter plot and regression line</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(data<span class="sc">$</span>Duration, data<span class="sc">$</span>Interval, <span class="at">main=</span><span class="st">"Old Faithful Eruption Interval vs. Duration"</span>, <span class="at">xlab=</span><span class="st">"Duration of Eruption (sec)"</span>, <span class="at">ylab=</span><span class="st">"Interval to Next Eruption (sec)"</span>)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(model, <span class="at">col=</span><span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="HW1_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="part-c-3" class="level3">
<h3 class="anchored" data-anchor-id="part-c-3">Part c</h3>
<section id="an-individual-has-just-arrived-at-the-end-of-an-eruption-that-lasted-250-seconds.-what-is-the-predicted-amount-of-time-the-individual-will-have-to-wait-until-the-next-eruption-calculate-a-95-prediction-interval-for-the-time-the-individual-will-have-to-wait-for-the-next-eruption." class="level4">
<h4 class="anchored" data-anchor-id="an-individual-has-just-arrived-at-the-end-of-an-eruption-that-lasted-250-seconds.-what-is-the-predicted-amount-of-time-the-individual-will-have-to-wait-until-the-next-eruption-calculate-a-95-prediction-interval-for-the-time-the-individual-will-have-to-wait-for-the-next-eruption.">An individual has just arrived at the end of an eruption that lasted 250 seconds. What is the predicted amount of time the individual will have to wait until the next eruption? Calculate a 95% prediction interval for the time the individual will have to wait for the next eruption.</h4>
<p>If an individual has arrived after a duration of 250 seconds we may predict the next eruption interval using r</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>estimate <span class="ot">=</span> <span class="fu">predict</span>(model, <span class="fu">data.frame</span>(<span class="at">Duration=</span><span class="dv">250</span>))</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Number of seconds till the next eruption:"</span>,estimate,<span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Number of seconds till the next eruption: 78.20354 </code></pre>
</div>
</div>
<p>We may also calculate the prediction interval using r</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Note the default for the predict function is a 95% interval</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>interval <span class="ot">=</span> <span class="fu">predict</span>(model,<span class="fu">data.frame</span>(<span class="at">Duration=</span><span class="dv">250</span>),<span class="at">interval=</span><span class="st">"prediction"</span>)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="co"># print the bounds</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Lower Bound:"</span>, interval[, <span class="st">"lwr"</span>], <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Lower Bound: 66.35401 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Upper Bound:"</span>, interval[, <span class="st">"upr"</span>], <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Upper Bound: 90.05307 </code></pre>
</div>
</div>
</section>
</section>
<section id="part-d-2" class="level3">
<h3 class="anchored" data-anchor-id="part-d-2">Part d</h3>
<section id="interpret-the-coefficient-of-determination-r2" class="level4">
<h4 class="anchored" data-anchor-id="interpret-the-coefficient-of-determination-r2">Interpret the coefficient of determination <span class="math inline">\((R^2)\)</span></h4>
<p>The coefficient of determination for our model is 0.8029, indicating that 80.29% of the variance in the data is explained by our model. The correlation between the duration of the last Old Faithful eruption and the time interval to the next interval is relatively strong. Our model may be used to predict eruption intervals, given the duration of the previous eruption. However the predictions cannot be relied upon to an extreme precision, given the extra variance not accounted for by our model. It may also be prudent to consider other variables related to Yellowstone’s geography or internal geyser chemistry that could account for the extra variance. It may also be useful to analyze eruption data from different dates for cross validation purposes.</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>